spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ${APP_NAME:My Simple Wallet}

  jackson:
    date-format: dd/MM/yyyy
    time-zone: America/Sao_Paulo

server:
  port: ${PORT:8080}


