# Configuração do profile de desenvolvimento
server:
  port: ${PORT:8080}

spring:
  jackson:
    time-zone: America/Sao_Paulo
  # Docker Compose Support para facilitar desenvolvimento
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  # Configuração do banco de dados H2 em memória para testes
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  # Configuração JPA/Hibernate
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true

h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    "org.hibernate.type.descriptor.sql.BasicBinder": TRACE


# # Configuração de logging para desenvolvimento
# logging:
#   level:
#     br.dev.mission.simplewallet: ${LOG_LEVEL:DEBUG}
#     org.springframework.web: ${WEB_LOG_LEVEL:INFO}
#     org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
#     org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:TRACE}

# # Configurações de desenvolvimento
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,metrics
#   endpoint:
#     health:
#       show-details: always


  
